// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: comment/v1/comment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Anchor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	BlockId       string                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	StartOffset   *int32                 `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3,oneof" json:"start_offset,omitempty"`
	EndOffset     *int32                 `protobuf:"varint,4,opt,name=end_offset,json=endOffset,proto3,oneof" json:"end_offset,omitempty"`
	SelectedText  string                 `protobuf:"bytes,5,opt,name=selected_text,json=selectedText,proto3" json:"selected_text,omitempty"`
	ContextBefore string                 `protobuf:"bytes,6,opt,name=context_before,json=contextBefore,proto3" json:"context_before,omitempty"`
	ContextAfter  string                 `protobuf:"bytes,7,opt,name=context_after,json=contextAfter,proto3" json:"context_after,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,8,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	TableId       string                 `protobuf:"bytes,9,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	RowId         string                 `protobuf:"bytes,10,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	ColumnId      string                 `protobuf:"bytes,11,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anchor) Reset() {
	*x = Anchor{}
	mi := &file_comment_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anchor) ProtoMessage() {}

func (x *Anchor) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anchor.ProtoReflect.Descriptor instead.
func (*Anchor) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Anchor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Anchor) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *Anchor) GetStartOffset() int32 {
	if x != nil && x.StartOffset != nil {
		return *x.StartOffset
	}
	return 0
}

func (x *Anchor) GetEndOffset() int32 {
	if x != nil && x.EndOffset != nil {
		return *x.EndOffset
	}
	return 0
}

func (x *Anchor) GetSelectedText() string {
	if x != nil {
		return x.SelectedText
	}
	return ""
}

func (x *Anchor) GetContextBefore() string {
	if x != nil {
		return x.ContextBefore
	}
	return ""
}

func (x *Anchor) GetContextAfter() string {
	if x != nil {
		return x.ContextAfter
	}
	return ""
}

func (x *Anchor) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *Anchor) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *Anchor) GetRowId() string {
	if x != nil {
		return x.RowId
	}
	return ""
}

func (x *Anchor) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

type BodyNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyNode) Reset() {
	*x = BodyNode{}
	mi := &file_comment_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyNode) ProtoMessage() {}

func (x *BodyNode) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyNode.ProtoReflect.Descriptor instead.
func (*BodyNode) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *BodyNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BodyNode) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *BodyNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BodyNode) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Thread struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageId          string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Anchor          *Anchor                `protobuf:"bytes,3,opt,name=anchor,proto3" json:"anchor,omitempty"`
	AnchorHash      string                 `protobuf:"bytes,4,opt,name=anchor_hash,json=anchorHash,proto3" json:"anchor_hash,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ResolvedBy      *string                `protobuf:"bytes,9,opt,name=resolved_by,json=resolvedBy,proto3,oneof" json:"resolved_by,omitempty"`
	ResolvedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=resolved_at,json=resolvedAt,proto3,oneof" json:"resolved_at,omitempty"`
	LastCommentedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_commented_at,json=lastCommentedAt,proto3,oneof" json:"last_commented_at,omitempty"`
	CommentsCount   int32                  `protobuf:"varint,12,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_comment_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{2}
}

func (x *Thread) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Thread) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *Thread) GetAnchor() *Anchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *Thread) GetAnchorHash() string {
	if x != nil {
		return x.AnchorHash
	}
	return ""
}

func (x *Thread) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Thread) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Thread) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Thread) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Thread) GetResolvedBy() string {
	if x != nil && x.ResolvedBy != nil {
		return *x.ResolvedBy
	}
	return ""
}

func (x *Thread) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *Thread) GetLastCommentedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCommentedAt
	}
	return nil
}

func (x *Thread) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

type ThreadWithComments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        *Thread                `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadWithComments) Reset() {
	*x = ThreadWithComments{}
	mi := &file_comment_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadWithComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadWithComments) ProtoMessage() {}

func (x *ThreadWithComments) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadWithComments.ProtoReflect.Descriptor instead.
func (*ThreadWithComments) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{3}
}

func (x *ThreadWithComments) GetThread() *Thread {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *ThreadWithComments) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type Comment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId        string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	ParentCommentId *string                `protobuf:"bytes,3,opt,name=parent_comment_id,json=parentCommentId,proto3,oneof" json:"parent_comment_id,omitempty"`
	AuthorId        string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Body            []*BodyNode            `protobuf:"bytes,5,rep,name=body,proto3" json:"body,omitempty"`
	BodyText        string                 `protobuf:"bytes,6,opt,name=body_text,json=bodyText,proto3" json:"body_text,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EditedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=edited_at,json=editedAt,proto3,oneof" json:"edited_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Status          string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_comment_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Comment) GetParentCommentId() string {
	if x != nil && x.ParentCommentId != nil {
		return *x.ParentCommentId
	}
	return ""
}

func (x *Comment) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Comment) GetBody() []*BodyNode {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Comment) GetBodyText() string {
	if x != nil {
		return x.BodyText
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Comment) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Comment) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Comment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Anchor        *Anchor                `protobuf:"bytes,2,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Body          []*BodyNode            `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThreadRequest) Reset() {
	*x = CreateThreadRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreadRequest) ProtoMessage() {}

func (x *CreateThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreadRequest.ProtoReflect.Descriptor instead.
func (*CreateThreadRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateThreadRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *CreateThreadRequest) GetAnchor() *Anchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *CreateThreadRequest) GetBody() []*BodyNode {
	if x != nil {
		return x.Body
	}
	return nil
}

type CreateThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        *Thread                `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	RootComment   *Comment               `protobuf:"bytes,2,opt,name=root_comment,json=rootComment,proto3" json:"root_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThreadResponse) Reset() {
	*x = CreateThreadResponse{}
	mi := &file_comment_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreadResponse) ProtoMessage() {}

func (x *CreateThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreadResponse.ProtoReflect.Descriptor instead.
func (*CreateThreadResponse) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *CreateThreadResponse) GetThread() *Thread {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *CreateThreadResponse) GetRootComment() *Comment {
	if x != nil {
		return x.RootComment
	}
	return nil
}

type ListThreadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsRequest) Reset() {
	*x = ListThreadsRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsRequest) ProtoMessage() {}

func (x *ListThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListThreadsRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{7}
}

func (x *ListThreadsRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ListThreadsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListThreadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListThreadsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Thread              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsResponse) Reset() {
	*x = ListThreadsResponse{}
	mi := &file_comment_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsResponse) ProtoMessage() {}

func (x *ListThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListThreadsResponse) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{8}
}

func (x *ListThreadsResponse) GetItems() []*Thread {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListDiscussionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiscussionsRequest) Reset() {
	*x = ListDiscussionsRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiscussionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiscussionsRequest) ProtoMessage() {}

func (x *ListDiscussionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiscussionsRequest.ProtoReflect.Descriptor instead.
func (*ListDiscussionsRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{9}
}

func (x *ListDiscussionsRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ListDiscussionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDiscussionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{10}
}

func (x *GetThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type GetThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ThreadWithComments    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadResponse) Reset() {
	*x = GetThreadResponse{}
	mi := &file_comment_v1_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadResponse) ProtoMessage() {}

func (x *GetThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadResponse.ProtoReflect.Descriptor instead.
func (*GetThreadResponse) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{11}
}

func (x *GetThreadResponse) GetItem() *ThreadWithComments {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Body          []*BodyNode            `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplyRequest) Reset() {
	*x = AddReplyRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplyRequest) ProtoMessage() {}

func (x *AddReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplyRequest.ProtoReflect.Descriptor instead.
func (*AddReplyRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{12}
}

func (x *AddReplyRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *AddReplyRequest) GetBody() []*BodyNode {
	if x != nil {
		return x.Body
	}
	return nil
}

type AddReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplyResponse) Reset() {
	*x = AddReplyResponse{}
	mi := &file_comment_v1_comment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplyResponse) ProtoMessage() {}

func (x *AddReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplyResponse.ProtoReflect.Descriptor instead.
func (*AddReplyResponse) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{13}
}

func (x *AddReplyResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type ChangeThreadStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeThreadStateRequest) Reset() {
	*x = ChangeThreadStateRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeThreadStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeThreadStateRequest) ProtoMessage() {}

func (x *ChangeThreadStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeThreadStateRequest.ProtoReflect.Descriptor instead.
func (*ChangeThreadStateRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeThreadStateRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type FollowThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowThreadRequest) Reset() {
	*x = FollowThreadRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowThreadRequest) ProtoMessage() {}

func (x *FollowThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowThreadRequest.ProtoReflect.Descriptor instead.
func (*FollowThreadRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{16}
}

func (x *FollowThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

var File_comment_v1_comment_proto protoreflect.FileDescriptor

const file_comment_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x18comment/v1/comment.proto\x12\n" +
	"comment.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x03\n" +
	"\x06Anchor\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\tR\ablockId\x12&\n" +
	"\fstart_offset\x18\x03 \x01(\x05H\x00R\vstartOffset\x88\x01\x01\x12\"\n" +
	"\n" +
	"end_offset\x18\x04 \x01(\x05H\x01R\tendOffset\x88\x01\x01\x12#\n" +
	"\rselected_text\x18\x05 \x01(\tR\fselectedText\x12%\n" +
	"\x0econtext_before\x18\x06 \x01(\tR\rcontextBefore\x12#\n" +
	"\rcontext_after\x18\a \x01(\tR\fcontextAfter\x12\x1f\n" +
	"\vsnapshot_id\x18\b \x01(\tR\n" +
	"snapshotId\x12\x19\n" +
	"\btable_id\x18\t \x01(\tR\atableId\x12\x15\n" +
	"\x06row_id\x18\n" +
	" \x01(\tR\x05rowId\x12\x1b\n" +
	"\tcolumn_id\x18\v \x01(\tR\bcolumnIdB\x0f\n" +
	"\r_start_offsetB\r\n" +
	"\v_end_offset\"a\n" +
	"\bBodyNode\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xbd\x04\n" +
	"\x06Thread\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\x12*\n" +
	"\x06anchor\x18\x03 \x01(\v2\x12.comment.v1.AnchorR\x06anchor\x12\x1f\n" +
	"\vanchor_hash\x18\x04 \x01(\tR\n" +
	"anchorHash\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\vresolved_by\x18\t \x01(\tH\x00R\n" +
	"resolvedBy\x88\x01\x01\x12@\n" +
	"\vresolved_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"resolvedAt\x88\x01\x01\x12K\n" +
	"\x11last_commented_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x0flastCommentedAt\x88\x01\x01\x12%\n" +
	"\x0ecomments_count\x18\f \x01(\x05R\rcommentsCountB\x0e\n" +
	"\f_resolved_byB\x0e\n" +
	"\f_resolved_atB\x14\n" +
	"\x12_last_commented_at\"q\n" +
	"\x12ThreadWithComments\x12*\n" +
	"\x06thread\x18\x01 \x01(\v2\x12.comment.v1.ThreadR\x06thread\x12/\n" +
	"\bcomments\x18\x02 \x03(\v2\x13.comment.v1.CommentR\bcomments\"\x8a\x04\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12/\n" +
	"\x11parent_comment_id\x18\x03 \x01(\tH\x00R\x0fparentCommentId\x88\x01\x01\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12(\n" +
	"\x04body\x18\x05 \x03(\v2\x14.comment.v1.BodyNodeR\x04body\x12\x1b\n" +
	"\tbody_text\x18\x06 \x01(\tR\bbodyText\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\tedited_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x01R\beditedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tdeletedAt\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06statusB\x14\n" +
	"\x12_parent_comment_idB\f\n" +
	"\n" +
	"_edited_atB\r\n" +
	"\v_deleted_at\"\x84\x01\n" +
	"\x13CreateThreadRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12*\n" +
	"\x06anchor\x18\x02 \x01(\v2\x12.comment.v1.AnchorR\x06anchor\x12(\n" +
	"\x04body\x18\x03 \x03(\v2\x14.comment.v1.BodyNodeR\x04body\"z\n" +
	"\x14CreateThreadResponse\x12*\n" +
	"\x06thread\x18\x01 \x01(\v2\x12.comment.v1.ThreadR\x06thread\x126\n" +
	"\froot_comment\x18\x02 \x01(\v2\x13.comment.v1.CommentR\vrootComment\"|\n" +
	"\x12ListThreadsRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"?\n" +
	"\x13ListThreadsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.comment.v1.ThreadR\x05items\"_\n" +
	"\x16ListDiscussionsRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"/\n" +
	"\x10GetThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"G\n" +
	"\x11GetThreadResponse\x122\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.comment.v1.ThreadWithCommentsR\x04item\"X\n" +
	"\x0fAddReplyRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12(\n" +
	"\x04body\x18\x02 \x03(\v2\x14.comment.v1.BodyNodeR\x04body\"A\n" +
	"\x10AddReplyResponse\x12-\n" +
	"\acomment\x18\x01 \x01(\v2\x13.comment.v1.CommentR\acomment\"7\n" +
	"\x18ChangeThreadStateRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"5\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\"2\n" +
	"\x13FollowThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId2\x98\x06\n" +
	"\x0eCommentService\x12Q\n" +
	"\fCreateThread\x12\x1f.comment.v1.CreateThreadRequest\x1a .comment.v1.CreateThreadResponse\x12N\n" +
	"\vListThreads\x12\x1e.comment.v1.ListThreadsRequest\x1a\x1f.comment.v1.ListThreadsResponse\x12V\n" +
	"\x0fListDiscussions\x12\".comment.v1.ListDiscussionsRequest\x1a\x1f.comment.v1.ListThreadsResponse\x12H\n" +
	"\tGetThread\x12\x1c.comment.v1.GetThreadRequest\x1a\x1d.comment.v1.GetThreadResponse\x12E\n" +
	"\bAddReply\x12\x1b.comment.v1.AddReplyRequest\x1a\x1c.comment.v1.AddReplyResponse\x12M\n" +
	"\rResolveThread\x12$.comment.v1.ChangeThreadStateRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\fReopenThread\x12$.comment.v1.ChangeThreadStateRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rDeleteComment\x12 .comment.v1.DeleteCommentRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\fFollowThread\x12\x1f.comment.v1.FollowThreadRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eUnfollowThread\x12\x1f.comment.v1.FollowThreadRequest\x1a\x16.google.protobuf.EmptyB'Z%github.com/flow-note/proto/comment/v1b\x06proto3"

var (
	file_comment_v1_comment_proto_rawDescOnce sync.Once
	file_comment_v1_comment_proto_rawDescData []byte
)

func file_comment_v1_comment_proto_rawDescGZIP() []byte {
	file_comment_v1_comment_proto_rawDescOnce.Do(func() {
		file_comment_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_v1_comment_proto_rawDesc), len(file_comment_v1_comment_proto_rawDesc)))
	})
	return file_comment_v1_comment_proto_rawDescData
}

var file_comment_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_comment_v1_comment_proto_goTypes = []any{
	(*Anchor)(nil),                   // 0: comment.v1.Anchor
	(*BodyNode)(nil),                 // 1: comment.v1.BodyNode
	(*Thread)(nil),                   // 2: comment.v1.Thread
	(*ThreadWithComments)(nil),       // 3: comment.v1.ThreadWithComments
	(*Comment)(nil),                  // 4: comment.v1.Comment
	(*CreateThreadRequest)(nil),      // 5: comment.v1.CreateThreadRequest
	(*CreateThreadResponse)(nil),     // 6: comment.v1.CreateThreadResponse
	(*ListThreadsRequest)(nil),       // 7: comment.v1.ListThreadsRequest
	(*ListThreadsResponse)(nil),      // 8: comment.v1.ListThreadsResponse
	(*ListDiscussionsRequest)(nil),   // 9: comment.v1.ListDiscussionsRequest
	(*GetThreadRequest)(nil),         // 10: comment.v1.GetThreadRequest
	(*GetThreadResponse)(nil),        // 11: comment.v1.GetThreadResponse
	(*AddReplyRequest)(nil),          // 12: comment.v1.AddReplyRequest
	(*AddReplyResponse)(nil),         // 13: comment.v1.AddReplyResponse
	(*ChangeThreadStateRequest)(nil), // 14: comment.v1.ChangeThreadStateRequest
	(*DeleteCommentRequest)(nil),     // 15: comment.v1.DeleteCommentRequest
	(*FollowThreadRequest)(nil),      // 16: comment.v1.FollowThreadRequest
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 18: google.protobuf.Empty
}
var file_comment_v1_comment_proto_depIdxs = []int32{
	0,  // 0: comment.v1.Thread.anchor:type_name -> comment.v1.Anchor
	17, // 1: comment.v1.Thread.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: comment.v1.Thread.updated_at:type_name -> google.protobuf.Timestamp
	17, // 3: comment.v1.Thread.resolved_at:type_name -> google.protobuf.Timestamp
	17, // 4: comment.v1.Thread.last_commented_at:type_name -> google.protobuf.Timestamp
	2,  // 5: comment.v1.ThreadWithComments.thread:type_name -> comment.v1.Thread
	4,  // 6: comment.v1.ThreadWithComments.comments:type_name -> comment.v1.Comment
	1,  // 7: comment.v1.Comment.body:type_name -> comment.v1.BodyNode
	17, // 8: comment.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	17, // 9: comment.v1.Comment.updated_at:type_name -> google.protobuf.Timestamp
	17, // 10: comment.v1.Comment.edited_at:type_name -> google.protobuf.Timestamp
	17, // 11: comment.v1.Comment.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 12: comment.v1.CreateThreadRequest.anchor:type_name -> comment.v1.Anchor
	1,  // 13: comment.v1.CreateThreadRequest.body:type_name -> comment.v1.BodyNode
	2,  // 14: comment.v1.CreateThreadResponse.thread:type_name -> comment.v1.Thread
	4,  // 15: comment.v1.CreateThreadResponse.root_comment:type_name -> comment.v1.Comment
	2,  // 16: comment.v1.ListThreadsResponse.items:type_name -> comment.v1.Thread
	3,  // 17: comment.v1.GetThreadResponse.item:type_name -> comment.v1.ThreadWithComments
	1,  // 18: comment.v1.AddReplyRequest.body:type_name -> comment.v1.BodyNode
	4,  // 19: comment.v1.AddReplyResponse.comment:type_name -> comment.v1.Comment
	5,  // 20: comment.v1.CommentService.CreateThread:input_type -> comment.v1.CreateThreadRequest
	7,  // 21: comment.v1.CommentService.ListThreads:input_type -> comment.v1.ListThreadsRequest
	9,  // 22: comment.v1.CommentService.ListDiscussions:input_type -> comment.v1.ListDiscussionsRequest
	10, // 23: comment.v1.CommentService.GetThread:input_type -> comment.v1.GetThreadRequest
	12, // 24: comment.v1.CommentService.AddReply:input_type -> comment.v1.AddReplyRequest
	14, // 25: comment.v1.CommentService.ResolveThread:input_type -> comment.v1.ChangeThreadStateRequest
	14, // 26: comment.v1.CommentService.ReopenThread:input_type -> comment.v1.ChangeThreadStateRequest
	15, // 27: comment.v1.CommentService.DeleteComment:input_type -> comment.v1.DeleteCommentRequest
	16, // 28: comment.v1.CommentService.FollowThread:input_type -> comment.v1.FollowThreadRequest
	16, // 29: comment.v1.CommentService.UnfollowThread:input_type -> comment.v1.FollowThreadRequest
	6,  // 30: comment.v1.CommentService.CreateThread:output_type -> comment.v1.CreateThreadResponse
	8,  // 31: comment.v1.CommentService.ListThreads:output_type -> comment.v1.ListThreadsResponse
	8,  // 32: comment.v1.CommentService.ListDiscussions:output_type -> comment.v1.ListThreadsResponse
	11, // 33: comment.v1.CommentService.GetThread:output_type -> comment.v1.GetThreadResponse
	13, // 34: comment.v1.CommentService.AddReply:output_type -> comment.v1.AddReplyResponse
	18, // 35: comment.v1.CommentService.ResolveThread:output_type -> google.protobuf.Empty
	18, // 36: comment.v1.CommentService.ReopenThread:output_type -> google.protobuf.Empty
	18, // 37: comment.v1.CommentService.DeleteComment:output_type -> google.protobuf.Empty
	18, // 38: comment.v1.CommentService.FollowThread:output_type -> google.protobuf.Empty
	18, // 39: comment.v1.CommentService.UnfollowThread:output_type -> google.protobuf.Empty
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_comment_v1_comment_proto_init() }
func file_comment_v1_comment_proto_init() {
	if File_comment_v1_comment_proto != nil {
		return
	}
	file_comment_v1_comment_proto_msgTypes[0].OneofWrappers = []any{}
	file_comment_v1_comment_proto_msgTypes[2].OneofWrappers = []any{}
	file_comment_v1_comment_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_v1_comment_proto_rawDesc), len(file_comment_v1_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_v1_comment_proto_goTypes,
		DependencyIndexes: file_comment_v1_comment_proto_depIdxs,
		MessageInfos:      file_comment_v1_comment_proto_msgTypes,
	}.Build()
	File_comment_v1_comment_proto = out.File
	file_comment_v1_comment_proto_goTypes = nil
	file_comment_v1_comment_proto_depIdxs = nil
}
